tsimcoal

~/bin/fsc26_linux64/fsc26 -i ~/urchin_af/analysis/simulations/test.par -n 1


# recombination rate:
    # Construction of a High-Density Genetic Map and Quantitative Trait Locus Mapping in the Sea Cucumber Apostichopus japonicus
        # 0.0975 cM/Mb or 9.75e-08 cM/base or 0.0000000975
# mutation rate
   # 0.00000008; 8e-8

# using arlsumstats to calculate diversity output

# need to generate a arl_run.ars file.
    # probably yhe best way to do this is using arlequin

#The following command will analyse the file test.arp and write the summary
#statistics in the file outSS.txt, which will be reset, and which will begin
#with a header line with the names of the summary statistics:


 A mutation rate of math formula mutation per site per generation was used, which implies that math formula

 theta=4*Ne*u

perhaps use melanies estimation?????


####
# example bash script

#!/bin/bash

cd ~/urchin_af/analysis/simulations

#Name of the simcoal parameter file
parameterFile=test.par
#Name of the files containing computed summary statistics
outss=outss.txt

# run simulation
# options contained in test.par file
# n means how many reps to run
~/bin/fsc26_linux64/fsc26 -i ~/urchin_af/analysis/simulations/test.par -n 2

###
# calculate summary stats. check diversity, etc of sims

#Move to directory containing arlequin files generated by simcoal2
cd ${parameterFile%.*}
cp ~/bin/arlsumstat_linux/arlsumstat3522_64bit .
cp ../arl_run.ars .
cp ../ssdefs.txt .
counter=1;
for file in *.arp
do
   echo "Processing file $file"
   if [ $counter -eq 1 ];  then
      #Compute stats, reset output file "outss.txt" and include header
      ./arlsumstat3522_64bit  ./$file $outss 0 1 run_silent
   else
      #Compute stats and just append stats in output file "outss.txt"
      ./arlsumstat3522_64bit ./$file $outss 1 0 run_silent
   fi
   let counter=counter+1
done
#Remove result directory created by arlsumstat
rm *.res -r
mv $outss ..
cd ..

# results saved in outss.txt

cat outss.txt | cut -f 10-

# look at mean_Pi column
# this is total pairwise diff. I want pi/base.
# take mean_Pi/total bases

#mean_Pi/(numloci * base length of each)
#mean_Pi/(21695 * 600)

#102778/(21695 * 600) = 0.007 # Ne = 50k

